In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [2]:
student = pd.read_csv("student_performance_updated_1000.csv.xls")

print("Cleaned Dataset:")
student.head()


Cleaned Dataset:


,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True


In [3]:
print("\nDataset Shape:", student.shape)
print("\n No of Rows:", student.shape[0])
print("\n No of Columns:", student.shape[1])



Dataset Shape: (1000, 12)

 No of Rows: 1000

 No of Columns: 12


In [4]:
student["Grade_Category"] = np.where(
    student["FinalGrade"] >= 75,
    "Pass",
    "Fail"
)
print(student["Grade_Category"].value_counts())


Grade_Category
Pass    667
Fail    333
Name: count, dtype: int64


In [5]:
X = student.drop(["FinalGrade", "Grade_Category"], axis=1)
y = student["Grade_Category"]
print("\nFeatures:")
print(X.head())



Features:
   StudentID     Name  Gender  AttendanceRate  StudyHoursPerWeek  \
0        1.0     John    Male            85.0               15.0   
1        2.0    Sarah  Female            90.0               20.0   
2        3.0     Alex    Male            78.0               10.0   
3        4.0  Michael    Male            92.0               25.0   
4        5.0     Emma  Female             NaN               18.0   

   PreviousGrade  ExtracurricularActivities ParentalSupport  Study Hours  \
0           78.0                        1.0            High          4.8   
1           85.0                        2.0          Medium          2.2   
2           65.0                        0.0             Low          4.6   
3           90.0                        3.0            High          2.9   
4           82.0                        2.0          Medium          4.1   

   Attendance (%) Online Classes Taken  
0            59.0                False  
1            70.0                 True  


In [6]:
print("\nTarget:")
print(y.head())



Target:
0    Pass
1    Pass
2    Fail
3    Pass
4    Pass
Name: Grade_Category, dtype: object


In [7]:
X_train, X_test, y_train, y_test = train_test_split( 	   X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y)
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)


X_train: (800, 11)
X_test : (200, 11)
y_train: (800,)
y_test : (200,)


In [8]:
# Remove non-numeric columns
X_train = X_train.drop(columns=['StudentID', 'Name'], errors='ignore')
X_test = X_test.drop(columns=['StudentID', 'Name'], errors='ignore')

# Keep only numeric columns
X_train = X_train.select_dtypes(include='number')
X_test = X_test.select_dtypes(include='number')

# Scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled Training Data:")
print(X_train_scaled[:5])

print("\nTraining Shape:", X_train_scaled.shape)
print("Testing Shape:", X_test_scaled.shape)

Scaled Training Data:
[[-2.11176757 -0.41751139 -1.79294301 -0.50264116  0.53501384 -1.1913038 ]
 [-2.11176757 -0.09628367 -0.07939231 -0.50264116 -1.19579675  0.313433  ]
 [-0.47374253  0.38555791 -0.78497201 -1.44617394  0.47319918 -0.20544176]
 [ 1.30078459 -0.89935298  0.82778159  0.44089163  0.53501384 -0.25732924]
 [-0.06423628  0.06433019  0.42459319  1.38442441 -1.50487007  0.41720795]]

Training Shape: (800, 6)
Testing Shape: (200, 6)


In [9]:
print("\nScaled Testing Data:")
print(X_test_scaled[:5])



Scaled Testing Data:
[[ 1.30078459  0.38555791  0.72698449 -0.50264116 -0.57765011  0.57287038]
 [ 1.30078459  1.18862722 -0.07939231 -0.50264116  0.84408716  0.83230776]
 [ 1.30078459  1.99169652 -0.07939231 -0.50264116  0.04049653         nan]
 [        nan  0.70678563 -1.28895751  0.44089163  0.65864317 -1.03564138]
 [-0.06423628 -0.09628367 -1.28895751 -0.50264116 -0.70127944  0.88419523]]


In [10]:
from sklearn.impute import SimpleImputer
from sklearn.svm import SVC

# Fill missing values
imputer = SimpleImputer(strategy="median")

X_train_clean = imputer.fit_transform(X_train_scaled)
X_test_clean = imputer.transform(X_test_scaled)

# Create SVM model
svm_model = SVC(
    kernel="rbf",
    C=1.0,
    random_state=42
)

# Train model
svm_model.fit(X_train_clean, y_train)

print("SVM model trained successfully.")

SVM model trained successfully.


In [11]:
# Prediction using cleaned test data
y_pred = svm_model.predict(X_test_clean)

print("\nPredicted Values:")
print(y_pred[:20])


Predicted Values:
['Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass'
 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [12]:
print("\nActual Values:")
print(y_test.values[:20])




Actual Values:
['Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass'
 'Pass' 'Fail' 'Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail']


In [13]:
baseline_accuracy = y_test.value_counts().max() / len(y_test)
print("Baseline Accuracy:", baseline_accuracy)
print("Baseline Accuracy (%):", baseline_accuracy * 100)


Baseline Accuracy: 0.665
Baseline Accuracy (%): 66.5


In [14]:
accuracy = accuracy_score(y_test, y_pred)
print("SVM Accuracy:", accuracy)
print("SVM Accuracy (%):", accuracy * 100)


SVM Accuracy: 0.655
SVM Accuracy (%): 65.5


In [15]:
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)



Confusion Matrix:
[[  0  67]
 [  2 131]]


In [16]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))



Classification Report:
              precision    recall  f1-score   support

        Fail       0.00      0.00      0.00        67
        Pass       0.66      0.98      0.79       133

    accuracy                           0.66       200
   macro avg       0.33      0.49      0.40       200
weighted avg       0.44      0.66      0.53       200



In [17]:
kernels = ['linear', 'poly', 'rbf', 'sigmoid']

for kernel in kernels:
    model = SVC(kernel=kernel, C=1.0, random_state=42)
    model.fit(X_train_clean, y_train)

    prediction = model.predict(X_test_clean)
    accuracy = accuracy_score(y_test, prediction)

    print("Kernel:", kernel)
    print("Accuracy:", accuracy)
    print("-" * 30)

Kernel: linear
Accuracy: 0.665
------------------------------
Kernel: poly
Accuracy: 0.66
------------------------------
Kernel: rbf
Accuracy: 0.655
------------------------------
Kernel: sigmoid
Accuracy: 0.62
------------------------------


In [18]:
print("Training class distribution:")
print(y_train.value_counts())

print("\nTesting class distribution:")
print(y_test.value_counts())


Training class distribution:
Grade_Category
Pass    534
Fail    266
Name: count, dtype: int64

Testing class distribution:
Grade_Category
Pass    133
Fail     67
Name: count, dtype: int64
